services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.37.10
    container_name: n8n_local
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Lima
      - TZ=America/Lima
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_EDITOR_BASE_URL=http://localhost:5678/
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    container_name: finedu_frontend
    ports:
      - "8080:8080"
      - "5000:80"
    restart: unless-stopped

volumes:
  n8n_data:
